application: dansffoodtrucks
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: sffoodtrucks/static

- url: .*
  script: application.application

libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on